package com.ShawnYin.WSP.mapper;

import com.ShawnYin.WSP.entity.subTask2;
import com.ShawnYin.WSP.entity.subTask2Key;

public interface subTask2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(subTask2Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask2
     *
     * @mbggenerated
     */
    int insert(subTask2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask2
     *
     * @mbggenerated
     */
    int insertSelective(subTask2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask2
     *
     * @mbggenerated
     */
    subTask2 selectByPrimaryKey(subTask2Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(subTask2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(subTask2 record);
}