package com.ShawnYin.WSP.entity;

import java.util.Date;

public class subTask2Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.device_Id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Id
     *
     * @mbggenerated
     */
    private Integer targetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.time
     *
     * @return the value of subtask2.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.time
     *
     * @param time the value for subtask2.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.device_Id
     *
     * @return the value of subtask2.device_Id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.device_Id
     *
     * @param deviceId the value for subtask2.device_Id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Id
     *
     * @return the value of subtask2.target_Id
     *
     * @mbggenerated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Id
     *
     * @param targetId the value for subtask2.target_Id
     *
     * @mbggenerated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }
}