package com.ShawnYin.WSP.entity;

public class subTask2 extends subTask2Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Pos_X
     *
     * @mbggenerated
     */
    private Double targetPosX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Pos_Y
     *
     * @mbggenerated
     */
    private Double targetPosY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Pos_Z
     *
     * @mbggenerated
     */
    private Double targetPosZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Vel_X
     *
     * @mbggenerated
     */
    private Double targetVelX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Vel_Y
     *
     * @mbggenerated
     */
    private Double targetVelY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Vel_Z
     *
     * @mbggenerated
     */
    private Double targetVelZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Acc_X
     *
     * @mbggenerated
     */
    private Double targetAccX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Acc_Y
     *
     * @mbggenerated
     */
    private Double targetAccY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask2.target_Acc_Z
     *
     * @mbggenerated
     */
    private Double targetAccZ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Pos_X
     *
     * @return the value of subtask2.target_Pos_X
     *
     * @mbggenerated
     */
    public Double getTargetPosX() {
        return targetPosX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Pos_X
     *
     * @param targetPosX the value for subtask2.target_Pos_X
     *
     * @mbggenerated
     */
    public void setTargetPosX(Double targetPosX) {
        this.targetPosX = targetPosX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Pos_Y
     *
     * @return the value of subtask2.target_Pos_Y
     *
     * @mbggenerated
     */
    public Double getTargetPosY() {
        return targetPosY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Pos_Y
     *
     * @param targetPosY the value for subtask2.target_Pos_Y
     *
     * @mbggenerated
     */
    public void setTargetPosY(Double targetPosY) {
        this.targetPosY = targetPosY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Pos_Z
     *
     * @return the value of subtask2.target_Pos_Z
     *
     * @mbggenerated
     */
    public Double getTargetPosZ() {
        return targetPosZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Pos_Z
     *
     * @param targetPosZ the value for subtask2.target_Pos_Z
     *
     * @mbggenerated
     */
    public void setTargetPosZ(Double targetPosZ) {
        this.targetPosZ = targetPosZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Vel_X
     *
     * @return the value of subtask2.target_Vel_X
     *
     * @mbggenerated
     */
    public Double getTargetVelX() {
        return targetVelX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Vel_X
     *
     * @param targetVelX the value for subtask2.target_Vel_X
     *
     * @mbggenerated
     */
    public void setTargetVelX(Double targetVelX) {
        this.targetVelX = targetVelX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Vel_Y
     *
     * @return the value of subtask2.target_Vel_Y
     *
     * @mbggenerated
     */
    public Double getTargetVelY() {
        return targetVelY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Vel_Y
     *
     * @param targetVelY the value for subtask2.target_Vel_Y
     *
     * @mbggenerated
     */
    public void setTargetVelY(Double targetVelY) {
        this.targetVelY = targetVelY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Vel_Z
     *
     * @return the value of subtask2.target_Vel_Z
     *
     * @mbggenerated
     */
    public Double getTargetVelZ() {
        return targetVelZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Vel_Z
     *
     * @param targetVelZ the value for subtask2.target_Vel_Z
     *
     * @mbggenerated
     */
    public void setTargetVelZ(Double targetVelZ) {
        this.targetVelZ = targetVelZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Acc_X
     *
     * @return the value of subtask2.target_Acc_X
     *
     * @mbggenerated
     */
    public Double getTargetAccX() {
        return targetAccX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Acc_X
     *
     * @param targetAccX the value for subtask2.target_Acc_X
     *
     * @mbggenerated
     */
    public void setTargetAccX(Double targetAccX) {
        this.targetAccX = targetAccX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Acc_Y
     *
     * @return the value of subtask2.target_Acc_Y
     *
     * @mbggenerated
     */
    public Double getTargetAccY() {
        return targetAccY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Acc_Y
     *
     * @param targetAccY the value for subtask2.target_Acc_Y
     *
     * @mbggenerated
     */
    public void setTargetAccY(Double targetAccY) {
        this.targetAccY = targetAccY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask2.target_Acc_Z
     *
     * @return the value of subtask2.target_Acc_Z
     *
     * @mbggenerated
     */
    public Double getTargetAccZ() {
        return targetAccZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask2.target_Acc_Z
     *
     * @param targetAccZ the value for subtask2.target_Acc_Z
     *
     * @mbggenerated
     */
    public void setTargetAccZ(Double targetAccZ) {
        this.targetAccZ = targetAccZ;
    }
}